#python DeriveCSVPatches.py -n had_top_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>2.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X Hadr_Recoil_Pt -Y AK15Jet_Pt_0 ../../ntuples_2017/{TTTo*,ST*}/*nominal*.root
#python DeriveCSVPatches.py -n lep_qcd_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>150.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X M_W_transverse_0 -Y Evt_Pt_MET ../../ntuples_2017/QCD*/*nominal*.root

python DeriveCSVPatches.py -n lep_znunujets_2016 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1) || (Triggered_HLT_IsoMu24_vX==1 || Triggered_HLT_IsoTkMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/ZJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_wlnujets_2016 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1) || (Triggered_HLT_IsoMu24_vX==1 || Triggered_HLT_IsoTkMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/WJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_zlljets_2016 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1) || (Triggered_HLT_IsoMu24_vX==1 || Triggered_HLT_IsoTkMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/DYJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_gammajets_2016 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1) || (Triggered_HLT_IsoMu24_vX==1 || Triggered_HLT_IsoTkMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/GJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_ttbar_2016 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1) || (Triggered_HLT_IsoMu24_vX==1 || Triggered_HLT_IsoTkMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/TTTo*/*nominal*.root

python DeriveCSVPatches.py -n lep_singlet_2016 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1) || (Triggered_HLT_IsoMu24_vX==1 || Triggered_HLT_IsoTkMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/ST_*/*nominal*.root

python DeriveCSVPatches.py -n lep_diboson_2016 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1) || (Triggered_HLT_IsoMu24_vX==1 || Triggered_HLT_IsoTkMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/{WW*,ZZ*,WZ*}/*nominal*.root

python DeriveCSVPatches.py -n lep_qcd_2016 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1) || (Triggered_HLT_IsoMu24_vX==1 || Triggered_HLT_IsoTkMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/QCD*/*nominal*.root

python DeriveCSVPatches.py -n lep_vectormonotop_2016 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1) || (Triggered_HLT_IsoMu24_vX==1 || Triggered_HLT_IsoTkMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/Vector*/*nominal*.root




python DeriveCSVPatches.py -n lep_znunujets_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/ZJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_wlnujets_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/WJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_zlljets_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/DYJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_gammajets_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/GJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_ttbar_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/TTTo*/*nominal*.root

python DeriveCSVPatches.py -n lep_singlet_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/ST_*/*nominal*.root

python DeriveCSVPatches.py -n lep_diboson_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/{WW*,ZZ*,WZ*}/*nominal*.root

python DeriveCSVPatches.py -n lep_qcd_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/QCD*/*nominal*.root

python DeriveCSVPatches.py -n lep_vectormonotop_2017 -j 4 -S "(Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu27_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/Vector*/*nominal*.root




python DeriveCSVPatches.py -n lep_znunujets_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/ZJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_wlnujets_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/WJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_zlljets_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/DYJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_gammajets_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/GJets*/*nominal*.root

python DeriveCSVPatches.py -n lep_ttbar_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/TTTo*/*nominal*.root

python DeriveCSVPatches.py -n lep_singlet_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/ST_*/*nominal*.root

python DeriveCSVPatches.py -n lep_diboson_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/{WW*,ZZ*,WZ*}/*nominal*.root

python DeriveCSVPatches.py -n lep_qcd_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/QCD*/*nominal*.root

python DeriveCSVPatches.py -n lep_vectormonotop_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (Evt_Pt_MET>100.) && (N_LoosePhotons==0) && ((N_LooseElectrons+N_LooseMuons)==1) && ((N_TightElectrons+N_TightMuons)==1) && (N_Jets>=1) && (Jet_Pt[0]>80.) && (CaloMET_PFMET_ratio<1.0) && (DeltaPhi_AK4Jet_MET[0]>1.5) && (M_W_transverse[0]>40.) && ((Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1) || (Triggered_HLT_IsoMu24_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/Vector*/*nominal*.root




python DeriveCSVPatches.py -n had_znunujets_2016 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/ZJets*/*nominal*.root

python DeriveCSVPatches.py -n had_wlnujets_2016 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/WJets*/*nominal*.root

python DeriveCSVPatches.py -n had_zlljets_2016 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/DYJets*/*nominal*.root

python DeriveCSVPatches.py -n had_gammajets_2016 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/GJets*/*nominal*.root

python DeriveCSVPatches.py -n had_ttbar_2016 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/TTTo*/*nominal*.root

python DeriveCSVPatches.py -n had_singlet_2016 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/ST_*/*nominal*.root

python DeriveCSVPatches.py -n had_diboson_2016 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/{WW*,ZZ*,WZ*}/*nominal*.root

python DeriveCSVPatches.py -n had_qcd_2016 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2016_backup/QCD*/*nominal*.root

python DeriveCSVPatches.py -n had_vectormonotop_2016 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele27_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon175_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/Vector*/*nominal*.root




python DeriveCSVPatches.py -n had_znunujets_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/ZJets*/*nominal*.root

python DeriveCSVPatches.py -n had_wlnujets_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/WJets*/*nominal*.root

python DeriveCSVPatches.py -n had_zlljets_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/DYJets*/*nominal*.root

python DeriveCSVPatches.py -n had_gammajets_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/GJets*/*nominal*.root

python DeriveCSVPatches.py -n had_ttbar_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/TTTo*/*nominal*.root

python DeriveCSVPatches.py -n had_singlet_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/ST_*/*nominal*.root

python DeriveCSVPatches.py -n had_diboson_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/{WW*,ZZ*,WZ*}/*nominal*.root

python DeriveCSVPatches.py -n had_qcd_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2017/QCD*/*nominal*.root

python DeriveCSVPatches.py -n had_vectormonotop_2017 -j 4 -S "(Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele35_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/Vector*/*nominal*.root




python DeriveCSVPatches.py -n had_znunujets_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (N_HEM_AK15Jets==0) && (Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/ZJets*/*nominal*.root

python DeriveCSVPatches.py -n had_wlnujets_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (N_HEM_AK15Jets==0) && (Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/WJets*/*nominal*.root

python DeriveCSVPatches.py -n had_zlljets_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (N_HEM_AK15Jets==0) && (Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/DYJets*/*nominal*.root

python DeriveCSVPatches.py -n had_gammajets_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (N_HEM_AK15Jets==0) && (Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/GJets*/*nominal*.root

python DeriveCSVPatches.py -n had_ttbar_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (N_HEM_AK15Jets==0) && (Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/TTTo*/*nominal*.root

python DeriveCSVPatches.py -n had_singlet_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (N_HEM_AK15Jets==0) && (Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/ST_*/*nominal*.root

python DeriveCSVPatches.py -n had_diboson_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (N_HEM_AK15Jets==0) && (Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/{WW*,ZZ*,WZ*}/*nominal*.root

python DeriveCSVPatches.py -n had_qcd_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (N_HEM_AK15Jets==0) && (Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/QCD*/*nominal*.root

python DeriveCSVPatches.py -n had_vectormonotop_2018 -j 4 -S "(N_HEM_Jets==0) && (N_HEM_METS==0) && (N_HEM_AK15Jets==0) && (Hadr_Recoil_Pt>250.) && (N_AK15Jets==1) && (N_Jets>=1) && (N_Taus==0) && (DeltaPhi_AK15Jet_Hadr_Recoil[0]>1.5) && (AK15Jet_Pt[0]>200.) && ((Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60_vX == 1) || (Triggered_HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_vX == 1) || (Triggered_HLT_Ele32_WPTight_Gsf_vX==1) || (Triggered_HLT_Photon200_vX==1))" -X N_Jets -Y HT_AK4Jets ../../ntuples_2018/Vector*/*nominal*.root
