# Z(ll) boson scale factors
rootplot rootplot_config.py 2018/TheoryXS_eej_madgraph_2018.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{l}}[GeV]" --ylabel="Scale factor" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="SFs_2018" --noclean --title=2018 --legend-entries='Z(l#bar{l})'
rootplot rootplot_config.py 2017/TheoryXS_eej_madgraph_2017.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{l}}[GeV]" --ylabel="Scale factor" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="SFs_2017" --noclean --title=2017 --legend-entries='Z(l#bar{l})'
rootplot rootplot_config.py 2016/TheoryXS_eej_madgraph_2016.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{l}}[GeV]" --ylabel="Scale factor" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="SFs_2016" --noclean --title=2016 --legend-entries='Z(l#bar{l})'

# Z(ll) boson theory cross sections
rootplot rootplot_config.py eej.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{l}}[GeV]" --ylabel="#sigma_{TH}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="theory_xs" --noclean --legend-entries='Z(l#bar{l})' --title=' '
rootplot rootplot_config.py eej.root --processors=6 --size=1024x768 --xlabel="p_{T,l#bar{l}}[GeV]" --ylabel="#sigma_{TH}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="theory_xs" --noclean --path='(?i).*k.*' --legend-entries='Z(l#bar{l})' --title=' '
rootplot rootplot_config.py 2016/TheoryXS_eej_madgraph_2016.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{l}}[GeV]" --ylabel="#sigma_{TH}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="theory_xs" --noclean --path='.*prediction' --legend-entries='Z(l#bar{l})' --title=' '

# Z(ll) boson mc cross sections
rootplot rootplot_config.py 2018/Zll_boson_pt_madgraph_2018.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{l}}[GeV]" --ylabel="#sigma_{MC}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="mc_xs_2018" --noclean --title=2018 --legend-entries='Z(l#bar{l})'
rootplot rootplot_config.py 2017/Zll_boson_pt_madgraph_2017.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{l}}[GeV]" --ylabel="#sigma_{MC}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="mc_xs_2017" --noclean --title=2017 --legend-entries='Z(l#bar{l})'
rootplot rootplot_config.py 2016/Zll_boson_pt_madgraph_2016.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{l}}[GeV]" --ylabel="#sigma_{MC}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="mc_xs_2016" --noclean --title=2016 --legend-entries='Z(l#bar{l})'

# W(lnu) boson scale factors
rootplot rootplot_config.py 2018/TheoryXS_evj_madgraph_2018.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{#nu}_{l}}[GeV]" --ylabel="Scale factor" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="SFs_2018" --noclean --title=2018 --legend-entries='W(l#bar{#nu}_{l})'
rootplot rootplot_config.py 2017/TheoryXS_evj_madgraph_2017.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{#nu}_{l}}[GeV]" --ylabel="Scale factor" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="SFs_2017" --noclean --title=2017 --legend-entries='W(l#bar{#nu}_{l})'
rootplot rootplot_config.py 2016/TheoryXS_evj_madgraph_2016.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{#nu}_{l}}[GeV]" --ylabel="Scale factor" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="SFs_2016" --noclean --title=2016 --legend-entries='W(l#bar{#nu}_{l})'

# W(lnu) boson theory cross sections
rootplot rootplot_config.py evj.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{#nu}_{l}}[GeV]" --ylabel="#sigma_{TH}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="theory_xs" --noclean --legend-entries='W(l#bar{#nu}_{l})' --title=' '
rootplot rootplot_config.py evj.root --processors=6 --size=1024x768 --xlabel="p_{T,l#bar{#nu}_{l}}[GeV]" --ylabel="#sigma_{TH}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="theory_xs" --noclean --path='(?i).*k.*' --legend-entries='W(l#bar{#nu}_{l})' --title=' '
rootplot rootplot_config.py 2016/TheoryXS_evj_madgraph_2016.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{#nu}_{l}}[GeV]" --ylabel="#sigma_{TH}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="theory_xs" --noclean --path='.*prediction' --legend-entries='W(l#bar{#nu}_{l})' --title=' '

# W(lnu) boson mc cross sections
rootplot rootplot_config.py 2018/W_boson_pt_madgraph_2018.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{#nu}_{l}}[GeV]" --ylabel="#sigma_{MC}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="mc_xs_2018" --noclean --title=2018 --legend-entries='W(l#bar{#nu}_{l})'
rootplot rootplot_config.py 2017/W_boson_pt_madgraph_2017.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{#nu}_{l}}[GeV]" --ylabel="#sigma_{MC}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="mc_xs_2017" --noclean --title=2017 --legend-entries='W(l#bar{#nu}_{l})'
rootplot rootplot_config.py 2016/W_boson_pt_madgraph_2016.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,l#bar{#nu}_{l}}[GeV]" --ylabel="#sigma_{MC}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="mc_xs_2016" --noclean --title=2016 --legend-entries='W(l#bar{#nu}_{l})'

# Z(nunu) boson scale factors
rootplot rootplot_config.py 2018/TheoryXS_vvj_madgraph_2018.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,#nu#bar{#nu}}[GeV]" --ylabel="Scale factor" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="SFs_2018" --noclean --title=2018 --legend-entries='Z(#nu#bar{#nu})'
rootplot rootplot_config.py 2017/TheoryXS_vvj_madgraph_2017.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,#nu#bar{#nu}}[GeV]" --ylabel="Scale factor" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="SFs_2017" --noclean --title=2017 --legend-entries='Z(#nu#bar{#nu})'
rootplot rootplot_config.py 2016/TheoryXS_vvj_madgraph_2016.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,#nu#bar{#nu}}[GeV]" --ylabel="Scale factor" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="SFs_2016" --noclean --title=2016 --legend-entries='Z(#nu#bar{#nu})'

# Z(nunu) boson theory cross sections
rootplot rootplot_config.py vvj.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,#nu#bar{#nu}}[GeV]" --ylabel="#sigma_{TH}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="theory_xs" --noclean --legend-entries='Z(#nu#bar{#nu})' --title=' '
rootplot rootplot_config.py vvj.root --processors=6 --size=1024x768 --xlabel="p_{T,#nu#bar{#nu}}[GeV]" --ylabel="#sigma_{TH}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="theory_xs" --noclean --path='(?i).*k.*' --legend-entries='Z(#nu#bar{#nu})' --title=' '
rootplot rootplot_config.py 2016/TheoryXS_vvj_madgraph_2016.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,#nu#bar{#nu}}[GeV]" --ylabel="#sigma_{TH}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="theory_xs" --noclean --path='.*prediction' --legend-entries='Z(#nu#bar{#nu})' --title=' '

# Z(nunu) boson mc cross sections
rootplot rootplot_config.py 2018/Zvv_boson_pt_madgraph_2018.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,#nu#bar{#nu}}[GeV]" --ylabel="#sigma_{MC}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="mc_xs_2018" --noclean --title=2018 --legend-entries='Z(#nu#bar{#nu})'
rootplot rootplot_config.py 2017/Zvv_boson_pt_madgraph_2017.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,#nu#bar{#nu}}[GeV]" --ylabel="#sigma_{MC}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="mc_xs_2017" --noclean --title=2017 --legend-entries='Z(#nu#bar{#nu})'
rootplot rootplot_config.py 2016/Zvv_boson_pt_madgraph_2016.root --processors=6 --size=1024x768 --logy --xlabel="p_{T,#nu#bar{#nu}}[GeV]" --ylabel="#sigma_{MC}[pb]" --legend-location='upper right' --gridx --gridy --xmax=3000 -e pdf --draw='hist' --output="mc_xs_2016" --noclean --title=2016 --legend-entries='Z(#nu#bar{#nu})'
