python CalculateTransferFactors.py --signal_processes znunujets --signal_processes znunujets --signal_processes znunujets --signal_processes znunujets --signal_processes znunujets --signal_processes znunujets --signal_processes znunujets --signal_process ttbar --signal_process ttbar  --signal_process ttbar --signal_process ttbar  --signal_process ttbar --background_processes znunujets --background_processes zlljets --background_processes zlljets --background_processes wlnujets --background_processes wlnujets --background_processes gammajets --background_processes wlnujets --background_processes ttbar --background_processes ttbar --background_processes ttbar --background_processes ttbar --background_processes ttbar --signal_region had_SR --signal_region had_SR --signal_region had_SR --signal_region had_SR --signal_region had_SR --signal_region had_SR --signal_region had_SR --signal_region had_SR --signal_region had_SR --signal_region had_SR --signal_region had_SR --signal_region had_SR --background_regions had_SR --background_regions had_CR_ZElEl --background_regions had_CR_ZMuMu --background_regions had_CR_WEl --background_regions had_CR_WMu --background_regions had_CR_Gamma --background_regions had_SR --background_regions had_CR_ttbarEl --background_regions had_CR_ttbarMu --background_regions had_SR --background_regions had_CR_WEl --background_regions had_CR_WMu --variable Hadr_Recoil_Pt templates_original.root

python CalculateTransferFactors.py --signal_processes znunujets --background_processes znunujets --signal_region had_SR --background_regions had_SR \
                                   --signal_processes znunujets --background_processes wlnujets --signal_region had_SR --background_regions had_SR \
                                   --signal_processes znunujets --background_processes zlljets --signal_region had_SR --background_regions had_CR_ZElEl \
                                   --signal_processes znunujets --background_processes zlljets --signal_region had_SR --background_regions had_CR_ZMuMu \
                                   --signal_processes znunujets --background_processes wlnujets --signal_region had_SR --background_regions had_CR_WEl \
                                   --signal_processes znunujets --background_processes wlnujets --signal_region had_SR --background_regions had_CR_WMu \
                                   --signal_processes znunujets --background_processes gammajets --signal_region had_SR --background_regions had_CR_Gamma \
                                   --signal_processes ttbar --background_processes ttbar --signal_region had_SR --background_regions had_SR \
                                   --signal_processes ttbar --background_processes ttbar --signal_region had_SR --background_regions had_CR_ttbarEl \
                                   --signal_processes ttbar --background_processes ttbar --signal_region had_SR --background_regions had_CR_ttbarMu \
                                   --signal_processes ttbar --background_processes ttbar --signal_region had_SR --background_regions had_CR_WEl \
                                   --signal_processes ttbar --background_processes ttbar --signal_region had_SR --background_regions had_CR_WMu \
                                   templates_original.root
